### ISSUE TITLE
Helpful docs on using RFComm to bind to a device

### ISSUE THREAD

**Issue by justinturpin** [theacodes/phomemo_m02s#3]
Hello, I came across this after the official Phomemo app for android decided to stop working for me! I got this project to work and it works great on my Raspberry Pi, but I had to do a couple of things:

1. Bind the Bluetooth device to a serial port with rfcomm:
```bash
sudo rfcomm bind 0 00:15:83:5F:XX:XX
```
2. Use /dev/rfcomm0 when running the script:
```bash
python3 -m phomemo_m02s --port /dev/rfcomm0 myimage.jpg
```

Maybe we can add these docs to the readme to help out some other people? Thanks for this project!

**Comment by psranga** [comment]
@justinturpin  thx for the comment. I came here to get some confirmation on whether it works with Raspberry Pi OS.

And thank *you*, theacodes, for this project.
